#!/Users/faustoantonelli/Documents/Amb_VE/bin/python3.13
# -*- coding: utf-8 -*-
import re
import sys
from asammdf.gui.asammdfgui import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
