name: C++ CI
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Run Tests
        run: |
          docker build -t tc-test -f docker/Dockerfile .
          docker run --rm tc-test